task: door
model: extra_trees
door:
  canonical_length: 192
  continuous_channels: [Motor current(mA), Motor Voltage(10mV), Motor electrodynamic force, Door opening time(.1s), Door closing time(.1s), Door leaf position]
  state_channels: [Close command, Open command, DCSR, DCSL, DLSR, DLSL, Door Opened, Door Locked, Door is opening, Door is closing]

