"""Common prediction interfaces."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

import numpy as np


class ClassifierProtocol(Protocol):
    def fit(self, x: Any, y: Any) -> "ClassifierProtocol": ...
    def predict(self, x: Any) -> np.ndarray: ...
    def predict_proba(self, x: Any) -> np.ndarray: ...
    def save(self, path: str | Path) -> Path: ...
    def metadata(self) -> dict[str, Any]: ...


class RegressorProtocol(Protocol):
    def fit(self, x: Any, y: Any) -> "RegressorProtocol": ...
    def predict(self, x: Any) -> np.ndarray: ...
    def predict_interval(self, x: Any) -> tuple[np.ndarray, np.ndarray]: ...
    def save(self, path: str | Path) -> Path: ...
    def metadata(self) -> dict[str, Any]: ...

